version: '3.9'

networks:
  intranet:
    external: false
    driver: bridge

services:
  #
  # Keycloak
  #
  keycloak-db:
    container_name: keycloak-db
    image: postgres:13.11
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    networks:
      - intranet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 6
    restart: on-failure

  keycloak:
    depends_on:
      keycloak-db:
        condition: service_healthy
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1
    volumes:
      - ./config/keycloak/bank-realm.json:/opt/keycloak/data/import/bank-realm.json:ro
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    command: start-dev --import-realm
    ports:
      - 8080:8080
    networks:
      - intranet
    restart: on-failure

  #
  # upstreams
  #
  public-app-node1:
    container_name: public-app-node1
    image: nginx:1.25.0-alpine
    volumes:
      - ./config/upstream/public-app-node1.conf:/etc/nginx/nginx.conf:ro
    networks:
      - intranet
    restart: always

  public-app-node2:
    container_name: public-app-node2
    image: nginx:1.25.0-alpine
    volumes:
      - ./config/upstream/public-app-node2.conf:/etc/nginx/nginx.conf:ro
    networks:
      - intranet
    restart: always

  private-app-node1:
    container_name: private-app-node1
    image: nginx:1.25.0-alpine
    volumes:
      - ./config/upstream/private-app-node1.conf:/etc/nginx/nginx.conf:ro
    networks:
      - intranet
    restart: always

  private-app-node2:
    container_name: private-app-node2
    image: nginx:1.25.0-alpine
    volumes:
      - ./config/upstream/private-app-node2.conf:/etc/nginx/nginx.conf:ro
    networks:
      - intranet
    restart: always

  #
  # APISIX
  #
  etcd:
    container_name: etcd
    image: bitnami/etcd:3.5.9
    environment:
      APISIX_STAND_ALONE: "true"
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    networks:
      - intranet
    restart: always

  apisix:
    depends_on:
      - etcd
    container_name: apisix
    image: apache/apisix:3.3.0-debian
    volumes:
      - ./config/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - 9080:9080
    networks:
      - intranet
    restart: always

  apisix-config:
    depends_on:
      - apisix
    container_name: apisix-config
    image: nginx:1.25.0-alpine
    volumes:
      - ./config/apisix/config.sh:/apisix/config.sh:ro
    command: /apisix/config.sh
    networks:
      - intranet
    restart: on-failure
